//
// Copyright (c) 2019 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

loadGlobalLibrary()

def image_amd64
def image_arm64

pipeline {
    agent {
        label 'centos7-docker-4c-2g'
    }

    stages {
        stage('LF Prep') {
            steps {
                edgeXSetupEnvironment()
                edgeXDockerLogin(settingsFile: env.MVN_SETTINGS)
                script {
                    properties([pipelineTriggers([githubPush()])])
                }
            }
        }

        stage('Build Docker Image') {
            parallel {
                stage('Build amd64') {
                    agent {
                        label 'centos7-docker-4c-2g'
                    }
                    steps {
                        script {
                            docker.withRegistry("https://${env.DOCKER_REGISTRY}:10003") {
                                image_amd64 = docker.build('edgex-golang-base', '-f golang/Dockerfile ./golang')
                                
                                image_amd64.tag("latest")
                                image_amd64.tag(env.GIT_COMMIT)
                                image_amd64.tag("1.11.9-alpine")
                            }
                        }
                    }
                }

                stage('Build arm64') {
                    agent {
                        label 'ubuntu18.04-docker-arm64-4c-2g'
                    }
                    steps {
                        script {
                            docker.withRegistry("https://${env.DOCKER_REGISTRY}:10003") {
                                image_arm64 = docker.build('edgex-golang-base', '-f golang/Dockerfile ./golang')
                                
                                image_arm64.tag("arm64")
                                image_arm64.tag("${env.GIT_COMMIT}-arm64")
                                image_arm64.tag("1.11.9-alpine-arm64")
                            }
                        }
                    }
                }
            }
        }

        stage('Push Docker Image') {
            when { expression { edgex.isReleaseStream() } }
            steps {
                script {
                    docker.withRegistry("https://${env.DOCKER_REGISTRY}:10002") {
                        image_amd64.push()
                        image_arm64.push()
                    }
                }
            }
        }
    }

    post {
        always {
            edgeXInfraPublish()
        }
    }
}

def loadGlobalLibrary(branch = '*/master') {
    library(identifier: 'edgex-global-pipelines@master', 
        retriever: legacySCM([
            $class: 'GitSCM',
            userRemoteConfigs: [[url: 'https://github.com/edgexfoundry/edgex-global-pipelines.git']],
            branches: [[name: branch]],
            doGenerateSubmoduleConfigurations: false,
            extensions: [[
                $class: 'SubmoduleOption',
                recursiveSubmodules: true,
            ]]]
        )
    ) _
}