//
// Copyright (c) 2019 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

loadGlobalLibrary()

def image_amd64
def image_arm64
def changeDetected

pipeline {
    agent {
        label 'centos7-docker-4c-2g'
    }

    stages {
        stage('LF Prep') {
            steps {
                edgeXSetupEnvironment()
                script {
                    changeDetected = edgex.didChange('^golang/')
                    println "Detected Change in Golang? ${changeDetected}"
                }
            }
        }

        stage('Build Docker Image') {
            when { expression { changeDetected } }
            parallel {
                stage('amd64') {
                    agent {
                        label 'centos7-docker-4c-2g'
                    }
                    stages {
                        stage('Docker Build') {
                            steps {
                                edgeXDockerLogin(settingsFile: env.MVN_SETTINGS)

                                script {
                                    image_amd64 = docker.build('edgex-golang-base', '-f golang/Dockerfile ./golang')
                                }
                            }
                        }

                        stage('Docker Push') {
                            when { expression { edgex.isReleaseStream() } }
                            steps {
                                script {
                                    docker.withRegistry("https://${env.DOCKER_REGISTRY}:10003") {
                                        image_amd64.push("amd64")
                                        image_amd64.push(env.GIT_COMMIT)
                                        image_amd64.push("1.11.9-alpine")
                                    }
                                }
                            }
                        }
                    }
                }

                stage('arm64') {
                    agent {
                        label 'ubuntu18.04-docker-arm64-4c-2g'
                    }
                    stages {
                        stage('Docker Build') {
                            steps {
                                edgeXDockerLogin(settingsFile: env.MVN_SETTINGS)

                                script {
                                    image_arm64 = docker.build('edgex-golang-base', '-f golang/Dockerfile ./golang')
                                }
                            }
                        }

                        stage('Docker Push') {
                            when { expression { edgex.isReleaseStream() } }
                            steps {
                                script {
                                    docker.withRegistry("https://${env.DOCKER_REGISTRY}:10003") {
                                        image_arm64.push("arm64")
                                        image_arm64.push("${env.GIT_COMMIT}-arm64")
                                        image_arm64.push("1.11.9-alpine-arm64")
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    post {
        always {
            edgeXInfraPublish()
        }
    }
}

def loadGlobalLibrary(branch = '*/master') {
    library(identifier: 'edgex-global-pipelines@master', 
        retriever: legacySCM([
            $class: 'GitSCM',
            userRemoteConfigs: [[url: 'https://github.com/edgexfoundry/edgex-global-pipelines.git']],
            branches: [[name: branch]],
            doGenerateSubmoduleConfigurations: false,
            extensions: [[
                $class: 'SubmoduleOption',
                recursiveSubmodules: true,
            ]]]
        )
    ) _
}