pipeline {
    agent {
        label 'centos7-docker-4c-2g'
    }
    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    image = docker.build('robotframework', '-f robotframework/Dockerfile ./robotframework')
                }
            }
        }
    }

}
