//
// Copyright (c) 2019 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

loadGlobalLibrary()

def image_amd64
def changeDetected

pipeline {
    agent {
        label 'centos7-docker-4c-2g'
    }

    options {
        timestamps()
    }

    stages {
        stage('LF Prep') {
            steps {
                edgeXSetupEnvironment()
                edgeXDockerLogin(settingsFile: env.MVN_SETTINGS)
                script {
                    changeDetected = edgex.didChange('lftools')
                    println "Detected Change in LF Tools? ${changeDetected}"
                }
            }
        }

        stage('Build Docker Image') {
            when { expression { changeDetected } }
            steps {
                script {
                    image_amd64 = docker.build('edgex-lftools', '-f lftools/Dockerfile ./lftools')
                }
            }
        }

        stage('Push Docker Image') {
            when { allOf { expression { edgex.isReleaseStream() }; expression { changeDetected } } }
            steps {
                script {
                    docker.withRegistry("https://${env.DOCKER_REGISTRY}:10003") {
                        image_amd64.push("latest")
                        image_amd64.push(env.GIT_COMMIT)
                        image_amd64.push("0.23.1-centos7")
                    }
                }
            }
        }
    }

    post {
        always {
            edgeXInfraPublish()
        }
    }
}

def loadGlobalLibrary(branch = '*/master') {
    library(identifier: 'edgex-global-pipelines@master', 
        retriever: legacySCM([
            $class: 'GitSCM',
            userRemoteConfigs: [[url: 'https://github.com/edgexfoundry/edgex-global-pipelines.git']],
            branches: [[name: branch]],
            doGenerateSubmoduleConfigurations: false,
            extensions: [[
                $class: 'SubmoduleOption',
                recursiveSubmodules: true,
            ]]]
        )
    ) _
}