//
// Copyright (c) 2019 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

loadGlobalLibrary()

def image
def changeDetected

pipeline {
    agent {
        label 'centos7-docker-4c-2g'
    }

    options {
        timestamps()
    }

    environment {
        SNYK_VERSION = '1.217.3'
    }

    stages {
        stage('LF Prep') {
            steps {
                edgeXSetupEnvironment()
                script {
                    changeDetected = edgex.didChange('snyk')
                }
            }
        }

        stage('Build Docker Image') {
            when { expression { changeDetected } }

            steps {
                edgeXDockerLogin(settingsFile: env.MVN_SETTINGS)

                script {
                    image = docker.build('edgex-snyk-go', "-f snyk/Dockerfile --build-arg SNYK_VERSION=${env.SNYK_VERSION} ./snyk")
                }
            }
        }

        stage('Docker Push') {
            when { allOf { expression { edgex.isReleaseStream() }; expression { changeDetected } } }
            steps {
                script {
                    docker.withRegistry("https://${env.DOCKER_REGISTRY}:10003") {
                        image.push('latest')
                        image.push(env.SNYK_VERSION)
                    }
                }
            }
        }

        stage('Clair Image Scan') {
            when { allOf { expression { edgex.isReleaseStream() }; expression { changeDetected } } }
            steps {
                edgeXClair("${env.DOCKER_REGISTRY}:10003/edgex-snyk-go:${env.SNYK_VERSION}")
            }
        }
    }

    post {
        always {
            edgeXInfraPublish()
        }
    }
}

def loadGlobalLibrary(branch = '*/master') {
    library(identifier: 'edgex-global-pipelines@master', 
        retriever: legacySCM([
            $class: 'GitSCM',
            userRemoteConfigs: [[url: 'https://github.com/edgexfoundry/edgex-global-pipelines.git']],
            branches: [[name: branch]],
            doGenerateSubmoduleConfigurations: false,
            extensions: [
                [$class: 'SubmoduleOption', recursiveSubmodules: true],
                [$class: 'IgnoreNotifyCommit']
            ]
        ])
    ) _
}
