//
// Copyright (c) 2019 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

loadGlobalLibrary()

def image

pipeline {
    agent {
        label 'centos7-docker-4c-2g'
    }

    stages {
        stage('LF Prep') {
            steps {
                edgeXSetupEnvironment()
                edgeXDockerLogin(settingsFile: env.MVN_SETTINGS)
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker run --rm --privileged multiarch/qemu-user-static:register --reset'

                script {
                    docker.withRegistry("https://${env.DOCKER_REGISTRY}:10003") {
                        image = docker.build('kong-arm', '-f kong/Dockerfile ./kong')
                        
                        image.tag('latest')
                        image.tag(env.GIT_COMMIT)
                        image.tag(env.BUILD_NUMBER)
                    }
                }
            }
        }

        stage('Push Docker Image') {
            when { expression { edgex.isReleaseStream() } }
            steps {
                script {
                    docker.withRegistry("https://${env.DOCKER_REGISTRY}:10002") {
                        image.push()
                    }
                }
            }
        }
    }

    post {
        always {
            edgeXInfraPublish()
        }
    }
}

def loadGlobalLibrary(branch = '*/master') {
    library(identifier: 'edgex-global-pipelines@master', 
        retriever: legacySCM([
            $class: 'GitSCM',
            userRemoteConfigs: [[url: 'https://github.com/edgexfoundry/edgex-global-pipelines.git']],
            branches: [[name: branch]],
            doGenerateSubmoduleConfigurations: false,
            extensions: [[
                $class: 'SubmoduleOption',
                recursiveSubmodules: true,
            ]]]
        )
    ) _
}
