run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 120s

linters-settings:
  exclude: doc.go

linters:
  enable:
    - megacheck
    - govet
    - errcheck
    - staticcheck
    - unused    
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - unparam
    - interfacer
    - unconvert
    - misspell
    - goconst
  disable:
    - gosimple

# golangci.com configuration
# https://github.com/golangci/golangci/wiki/Configuration
service:
  golangci-lint-version: 1.16.x # use the fixed version to not introduce new linters unexpectedly